//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public System.DateTime Date { get; set; }
        public Nullable<float> OpeningBalance { get; set; }
        public Nullable<float> ClosingBalance { get; set; }
    }
}
