//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<float> PriceOverride { get; set; }
        public Nullable<float> CurrentPrice { get; set; }
    }
}
